# Generated by Django 3.2.9 on 2022-02-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_No', models.IntegerField()),
                ('Departure_Time', models.TimeField()),
                ('Destinations', models.CharField(max_length=50)),
                ('Seats_Available', models.IntegerField()),
                ('TicketCosts', models.IntegerField()),
            ],
        ),
    ]
